STARTING_SPELLS = {"confringo", "protego", "expelliarmus", "stupefy"}

QUIZ_RULES = {
    1: {"questions": 3, "required_score": 2},
    2: {"questions": 5, "required_score": 4},
    3: {"questions": 7, "required_score": 5},
    4: {"questions": 10, "required_score": 8},
    5: {"questions": 12, "required_score": 10},
}

SPELLS = {
    "confringo": {
        "display_name": "Confringo",
        "emoji": "🔥",
        "difficulty": 0,
        "starting": True,
        "categories": ["spells"],
        "requirements": {},
        "description": "A powerful offensive spell.",
    },
    "protego": {
        "display_name": "Protego",
        "emoji": "🛡️",
        "difficulty": 0,
        "starting": True,
        "categories": ["spells"],
        "requirements": {},
        "description": "A defensive shield spell.",
    },
    "expelliarmus": {
        "display_name": "Expelliarmus",
        "emoji": "⚡",
        "difficulty": 0,
        "starting": True,
        "categories": ["spells"],
        "requirements": {},
        "description": "A disarming spell that can also counter incoming magic.",
    },
"stupefy": {
    "display_name": "Stupefy",
    "emoji": "🔴",
    "difficulty": 0,
    "starting": True,
    "categories": [ "spells"],
    "requirements": {},
    "description": "A combat spell focused on control and interruption.",
},
    "incendio": {
        "display_name": "Incendio",
        "emoji": "🔥",
        "difficulty": 2,
        "starting": False,
        "categories": ["general", "spells"],
        "requirements": {
            "level": 2,
            "spell_levels": {"confringo": 2},
            "spell_hits": {"confringo": 5},
        },
        "description": "A fast fire spell (Spell Speed 9) with sustained burn damage.",
    },
    "diffindo": {
        "display_name": "Diffindo",
        "emoji": "✂️",
        "difficulty": 3,
        "starting": False,
        "categories": ["spells", "general"],
        "requirements": {
            "level": 3,
            "spell_levels": {"confringo": 3},
            "min_stats": {"magic_power": 18},
            "combat_stats": {"successful_attacks": 10},
        },
        "description": "A fast offensive spell designed to pressure Dodge.",
    },
    "depulso": {
        "display_name": "Depulso",
        "emoji": "💨",
        "difficulty": 3,
        "starting": False,
        "categories": ["spells", "general"],
        "requirements": {
            "level": 3,
            "spell_levels": {"expelliarmus": 2},
            "combat_stats": {"successful_counters": 3},
            "duel_wins": 2,
        },
        "description": "A control spell built around interruption and displacement.",
    },
    "glacius": {
        "display_name": "Glacius",
        "emoji": "❄️",
        "difficulty": 3,
        "starting": False,
        "categories": ["spells", "general"],
        "requirements": {
            "level": 3,
            "required_spells": ["stupefy"],
            "combat_stats": {"successful_control_spells": 5},
        },
        "description": "Reduces the opponent's Speed by 5 for 10 seconds when it lands.",
    },
    "petrificustotalus": {
        "display_name": "Petrificus Totalus",
        "emoji": "🗿",
        "difficulty": 3,
        "starting": False,
        "categories": ["spells", "hogwarts"],
        "requirements": {
            "level": 4,
            "spell_levels": {"stupefy": 2},
            "combat_stats": {"successful_control_spells": 5},
            "duel_wins": 3,
        },
        "description": "Deals light damage and stuns the opponent for 4 seconds.",
    },
    "bombarda": {
        "display_name": "Bombarda",
        "emoji": "💥",
        "difficulty": 4,
        "starting": False,
        "categories": ["spells", "general"],
        "requirements": {
            "level": 5,
            "spell_levels": {"confringo": 4, "incendio": 3},
            "min_stats": {"magic_power": 20},
            "duel_wins": 5,
            "required_spells": ["incendio"],
        },
        "description": "A heavy offensive spell. A successful Protego still takes 25% of its direct damage, rounded down.",
    },
    "sectumsempra": {
        "display_name": "Sectumsempra",
        "emoji": "🩸",
        "difficulty": 4,
        "starting": False,
        "categories": ["spells", "dark_arts", "characters"],
        "requirements": {
            "level": 5,
            "spell_levels": {"confringo": 3},
            "min_stats": {"magic_power": 20},
            "duel_wins": 5,
            "combat_stats": {
                "successful_attacks": 15,
                "successful_counters": 3,
            },
        },
        "description": "A cutting curse with heavy damage and bleeding. A successful Protego prevents bleeding but still takes 25% of direct damage, rounded down; strong shields or counters can cause backlash.",
    },
    "endoloris": {
        "display_name": "Endoloris",
        "emoji": "⚡",
        "difficulty": 4,
        "starting": False,
        "categories": ["dark_arts", "spells", "characters"],
        "requirements": {
            "level": 5,
            "spell_levels": {"stupefy": 3},
            "combat_stats": {"successful_control_spells": 10},
            "duel_wins": 5,
        },
        "description": "Initial d6 roll: 3–6 succeeds, 1–2 misses. No immediate damage. A hit causes 10 damage at 3, 6, and 9 seconds over a 10-second curse.",
    },
    "impero": {
        "display_name": "Impero",
        "emoji": "🌀",
        "difficulty": 4,
        "starting": False,
        "categories": ["dark_arts", "spells", "characters"],
        "requirements": {
            "level": 5,
            "spell_levels": {"petrificustotalus": 2},
            "combat_stats": {"successful_control_spells": 10},
            "duel_wins": 5,
        },
        "description": "Initial d6 roll: 4–6 succeeds, 1–3 misses. Forces the victim's highest-level learned offensive spell against themselves, with a fresh 10-second defense window. Never selects Avada Kedavra or Impero.",
    },
    "avadakedavra": {
        "display_name": "Avada Kedavra",
        "emoji": "💀",
        "difficulty": 5,
        "starting": False,
        "categories": ["dark_arts", "spells", "history", "characters"],
        "requirements": {
            "all_other_spells": True,
        },
        "description": "The ultimate Killing Curse. If it lands, the opponent is defeated instantly.",
    },}
