STARTING_SPELLS = {"confringo", "protego", "expelliarmus", "stupefy"}

QUIZ_RULES = {
    1: {"questions": 3, "required_score": 2},
    2: {"questions": 5, "required_score": 4},
    3: {"questions": 7, "required_score": 5},
    4: {"questions": 10, "required_score": 8},
    5: {"questions": 12, "required_score": 10},
}

SPELLS = {
    "confringo": {
        "display_name": "Confringo",
        "emoji": "🔥",
        "difficulty": 0,
        "starting": True,
        "categories": ["spells"],
        "requirements": {},
        "description": "A powerful offensive spell.",
    },
    "protego": {
        "display_name": "Protego",
        "emoji": "🛡️",
        "difficulty": 0,
        "starting": True,
        "categories": ["spells"],
        "requirements": {},
        "description": "A defensive shield spell.",
    },
    "expelliarmus": {
        "display_name": "Expelliarmus",
        "emoji": "⚡",
        "difficulty": 0,
        "starting": True,
        "categories": ["spells"],
        "requirements": {},
        "description": "A disarming spell that can also counter incoming magic.",
    },
"stupefy": {
    "display_name": "Stupefy",
    "emoji": "🔴",
    "difficulty": 0,
    "starting": True,
    "categories": [ "spells"],
    "requirements": {},
    "description": "A combat spell focused on control and interruption.",
},
    "incendio": {
        "display_name": "Incendio",
        "emoji": "🔥",
        "difficulty": 2,
        "starting": False,
        "categories": ["general", "spells"],
        "requirements": {
            "level": 2,
            "spell_levels": {"confringo": 2},
            "spell_hits": {"confringo": 5},
        },
        "description": "A fire spell intended for sustained offensive pressure.",
    },
    "levioso": {
        "display_name": "Levioso",
        "emoji": "🪶",
        "difficulty": 2,
        "starting": False,
        "categories": ["general", "spells", "hogwarts"],
        "requirements": {
            "level": 2,
            "duel_wins": 1,
            "combat_stats": {"successful_dodges": 3},
        },
        "description": "A control spell used to lift an opponent.",
    },
    "diffindo": {
        "display_name": "Diffindo",
        "emoji": "✂️",
        "difficulty": 3,
        "starting": False,
        "categories": ["spells", "general"],
        "requirements": {
            "level": 3,
            "spell_levels": {"confringo": 3},
            "min_stats": {"magic_power": 18},
            "combat_stats": {"successful_attacks": 10},
        },
        "description": "A fast offensive spell designed to pressure Dodge.",
    },
    "depulso": {
        "display_name": "Depulso",
        "emoji": "💨",
        "difficulty": 3,
        "starting": False,
        "categories": ["spells", "general"],
        "requirements": {
            "level": 3,
            "spell_levels": {"expelliarmus": 2},
            "combat_stats": {"successful_counters": 3},
            "duel_wins": 2,
        },
        "description": "A control spell built around interruption and displacement.",
    },
    "glacius": {
        "display_name": "Glacius",
        "emoji": "❄️",
        "difficulty": 3,
        "starting": False,
        "categories": ["spells", "general"],
        "requirements": {
            "level": 3,
            "required_spells": ["stupefy"],
            "combat_stats": {"successful_control_spells": 5},
        },
        "description": "A control spell planned to reduce an opponent's Speed.",
    },
    "petrificustotalus": {
        "display_name": "Petrificus Totalus",
        "emoji": "🗿",
        "difficulty": 3,
        "starting": False,
        "categories": ["spells", "hogwarts"],
        "requirements": {
            "level": 4,
            "spell_levels": {"levioso": 2},
            "spell_hits": {"levioso": 5},
            "duel_wins": 3,
        },
        "description": "An advanced control spell intended to briefly immobilize an opponent.",
    },
    "bombarda": {
        "display_name": "Bombarda",
        "emoji": "💥",
        "difficulty": 4,
        "starting": False,
        "categories": ["spells", "general"],
        "requirements": {
            "level": 5,
            "spell_levels": {"confringo": 4, "incendio": 3},
            "min_stats": {"magic_power": 20},
            "duel_wins": 5,
            "required_spells": ["incendio"],
        },
        "description": "A heavy offensive spell with high destructive potential.",
    },
    "arrestomomentum": {
        "display_name": "Arresto Momentum",
        "emoji": "⏳",
        "difficulty": 4,
        "starting": False,
        "categories": ["spells", "general"],
        "requirements": {
            "level": 5,
            "spell_levels": {"protego": 4},
            "combat_stats": {
                "successful_protegos": 10,
                "successful_dodges": 5,
            },
        },
        "description": "An advanced defensive/control spell intended to slow incoming magic.",
    },
    "sectumsempra": {
        "display_name": "Sectumsempra",
        "emoji": "🩸",
        "difficulty": 4,
        "starting": False,
        "categories": ["spells", "dark_arts", "characters"],
        "requirements": {
            "level": 5,
            "spell_levels": {"confringo": 3},
            "min_stats": {"magic_power": 20},
            "duel_wins": 5,
            "combat_stats": {
                "successful_attacks": 15,
                "successful_counters": 3,
            },
        },
        "description": "A dangerous cutting curse that causes heavy damage and bleeding.",
    },
    "avadakedavra": {
        "display_name": "Avada Kedavra",
        "emoji": "💀",
        "difficulty": 5,
        "starting": False,
        "categories": ["dark_arts", "spells", "history", "characters"],
        "requirements": {
            "all_other_spells": True,
        },
        "description": "The ultimate Killing Curse. If it lands, the opponent is defeated instantly.",
    },}
